version: '3.8'

services:
  # 1. Database: PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: system_internal_inl_postgres
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: system_internal_inl
    ports:
      - "5432:5432"
    volumes:
      # Lưu dữ liệu xuống ổ cứng máy Win 11 để không bị mất khi tắt container
      - postgres_data:/var/lib/postgresql/data
      # Tự động chạy script tạo bảng khi khởi động lần đầu
      - ./init-db:/docker-entrypoint-initdb.d

  # 2. Cache: Redis (Dùng cho blacklist JWT token khi logout)
  redis:
    image: redis:7-alpine
    container_name: system_internal_inl_redis
    restart: always
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # 3. Database Management: Adminer (Giao diện quản lý DB trên trình duyệt)
  adminer:
    image: adminer
    container_name: system_internal_inl_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  postgres_data:
  redis_data: